name: add-name-pronunciations
on:
  push
  # issues:
  #   types:
  #     - opened
jobs:
  grab-name-pronunciations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          declare -A pronunciation_map
          REGEXP="^- ([-'A-Za-zÀ-ÿ]+): (.*)$"
          while read n; do
            echo "$n"
            if [[ "$n" =~ $REGEXP ]]; then
                pronunciation_map["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
                echo pronuncation_map["${BASH_REMATCH[1]}"]
            fi
          done < name_pronunciations.md
