name: add-name-pronunciations
on:
  push
  # issues:
  #   types:
  #     - opened
jobs:
  grab-name-pronunciations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          declare -A pronunciation_map
          while read n; do
            echo "$n"
            if [[ "$n" =~ "(.*)" ]]; then
                #             if [[ "$n" =~ "- ([A-Za-zÀ-ÿ ]+): (.*)" ]]; then
                echo "what"
                pronunciation_map["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
                echo pronuncation_map["${BASH_REMATCH[1]}"]
            fi
          done < name_pronunciations.md
